Ap edit post
nss-day-cohort-46/rare-client-groovy-goblins pull request #20
Opened 2021-04-29 20:11 UTC by daprieu

# Description

user is able to click button `edit` and will be taken to a form where they can edit post. If user decides not to edit user can click cancel and will be taken back to `my post`

Fixes #15

## Type of change

- [x] New feature (non-breaking change which adds functionality)

- [x] This change requires a documentation update

# Testing Instructions

`git fetch --all`
`git checkout ap-editPost`

go to my post select edit

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

2021-04-29 21:11 UTC, Daniel-L-Ross requested changes
The form breaks when trying to add a new post. See note at line 68.

2021-04-29 21:11 UTC, Daniel-L-Ross commented on src/components/posts/PostForm.js
> +    const postbyId = posts.find(p => p.id === parseInt(urlId))
This runs every time the form loads, so when adding a new post postById is undefined, breaking the code. I think a conditional should fix this.

2021-04-30 14:44 UTC, Daniel-L-Ross approved these changes
tested and approved. Full functionality on both uses of the form.

2021-04-30 15:06 UTC, Daniel-L-Ross commented
@daprieu that conditional update looks great!

2021-04-30 15:08 UTC, CheoR approved these changes
Edit button does not show up if post does not belong to logged in user.

Logged in user can edit their post.

2021-04-30 15:10 UTC, merged